import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { sendContact } from './contactAPI';
import { RootState } from '../../app/store';

export type ContactData = {
    name: string,
    email: string,
    topic: string,
    message: string
}

export interface ContactState {
    status: 'sent' | 'sending' | 'not' | 'failed'
}

const initialState: ContactState = {
    status: 'not',
};

export const contactPost = createAsyncThunk(
    'contact/contactSave',
    async (contactData: ContactData) => {
        // The value we return becomes the `fulfilled` action payload
        const result = await sendContact(contactData.name, contactData.email, contactData.topic, contactData.message)
        return result.body;
    }
);

export const contactSlice = createSlice({
    name: 'contact',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(contactPost.pending, (state) => {
                state.status = 'sending';
            })
            .addCase(contactPost.fulfilled, (state, action) => {
                state.status = 'sent';
            })
            .addCase(contactPost.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

export const contactState = (state: RootState) => state.contact.status;


export default contactSlice.reducer;